import { useEffect, useMemo, useState } from "react";
import axios from "axios";
import toast from "react-hot-toast";
import { FiDownload, FiMail, FiPackage, FiSearch, FiTruck } from "react-icons/fi";
import { SellerEmpty, SellerHeader, SellerPage, StatusBadge } from "../components/SellerUI";

const statuses = ["All", "Pending", "Processing", "Confirmed", "Packed", "Shipped", "Delivered", "Cancellation Requested", "Cancelled", "Return Requested", "Return Approved", "Return Picked Up", "Returned", "Refund Pending", "Refunded", "RTO Initiated", "RTO Delivered"];
const nextStatuses = {
  Pending: ["Confirmed", "Cancelled"], Processing: ["Confirmed", "Packed", "Cancelled"], Confirmed: ["Packed", "Cancellation Requested", "Cancelled"], Packed: ["Shipped", "Cancelled"],
  Shipped: ["Delivered", "RTO Initiated"], Delivered: ["Return Requested"], "Cancellation Requested": ["Cancelled", "Confirmed"], "Return Requested": ["Return Approved", "Delivered"],
  "Return Approved": ["Return Picked Up"], "Return Picked Up": ["Returned"], Returned: ["Refund Pending"], "Refund Pending": ["Refunded"], "RTO Initiated": ["RTO Delivered"], "RTO Delivered": ["Refund Pending", "Cancelled"],
};
const money = (value) => Number.isFinite(Number(value)) ? `₹${Number(value).toFixed(2)}` : "—";
const courierMetric = (value, suffix = "") => value === undefined || value === null || value === "" ? "—" : `${value}${suffix}`;
const rankCouriers = (items = []) => {
  const valid = items.filter((item) => Number.isFinite(Number(item.rate)));
  if (!valid.length) return items;
  const rates = valid.map((item) => Number(item.rate)); const ratings = valid.map((item) => Number(item.rating)).filter(Number.isFinite);
  const minRate = Math.min(...rates); const maxRate = Math.max(...rates); const minRating = ratings.length ? Math.min(...ratings) : 0; const maxRating = ratings.length ? Math.max(...ratings) : 0;
  const score = (item) => { const costScore = maxRate === minRate ? 1 : (maxRate - Number(item.rate)) / (maxRate - minRate); const rating = Number(item.rating); const ratingScore = !Number.isFinite(rating) || maxRating === minRating ? 0.5 : (rating - minRating) / (maxRating - minRating); return costScore * 0.55 + ratingScore * 0.45; };
  return [...items].sort((left, right) => score(right) - score(left));
};

function AdminOrders() {
  const [orders, setOrders] = useState([]); const [search, setSearch] = useState(""); const [status, setStatus] = useState("All");
  const [expanded, setExpanded] = useState(null); const [drafts, setDrafts] = useState({}); const [loading, setLoading] = useState(true);
  const [couriers, setCouriers] = useState({}); const [shippingBusy, setShippingBusy] = useState({});
  const loadOrders = async () => { try { const { data } = await axios.get(`${import.meta.env.VITE_API_URL}/api/orders`); setOrders(Array.isArray(data) ? data : data.orders || []); } catch { toast.error("Could not load orders"); } finally { setLoading(false); } };
  useEffect(() => { let active = true; axios.get(`${import.meta.env.VITE_API_URL}/api/orders`).then(({ data }) => { if (active) setOrders(Array.isArray(data) ? data : data.orders || []); }).catch(() => { if (active) toast.error("Could not load orders"); }).finally(() => { if (active) setLoading(false); }); return () => { active = false; }; }, []);
  const filtered = useMemo(() => orders.filter((order) => { const term = search.toLowerCase(); return (!term || [order._id, order.customerName, order.phone, order.email, order.tracking?.trackingId].some((value) => String(value || "").toLowerCase().includes(term))) && (status === "All" || order.status === status); }), [orders, search, status]);
  const changeDraft = (id, key, value) => setDrafts((current) => ({ ...current, [id]: { ...current[id], [key]: value } }));
  const updateOrder = async (id, values, message) => { try { await axios.put(`${import.meta.env.VITE_API_URL}/api/orders/${id}`, values); toast.success(message); await loadOrders(); } catch (error) { toast.error(error.response?.data?.message || "Order could not be updated"); } };
  const download = async (id, type) => { try { const response = await axios.get(`${import.meta.env.VITE_API_URL}/api/orders/${type}/${id}`, { responseType: "blob" }); const url = URL.createObjectURL(response.data); const link = document.createElement("a"); link.href = url; link.download = `${type}-${id}.pdf`; link.click(); setTimeout(() => URL.revokeObjectURL(url), 30000); } catch { toast.error("Document download failed"); } };
  const resend = async (id) => { try { await axios.post(`${import.meta.env.VITE_API_URL}/api/orders/resend-invoice/${id}`); toast.success("Invoice sent"); } catch { toast.error("Invoice could not be sent"); } };
  const parcelBody = (order, draft) => ({ weight: draft.weight ?? order.shipping?.package?.weight ?? 0.5, length: draft.length ?? order.shipping?.package?.length ?? 15, breadth: draft.breadth ?? order.shipping?.package?.breadth ?? 12, height: draft.height ?? order.shipping?.package?.height ?? 5 });
  const shippingAction = async (order, action, body = {}, success = "Shipping updated") => {
    const id = String(order._id); setShippingBusy((value) => ({ ...value, [id]: action }));
    try { const { data } = await axios.post(`${import.meta.env.VITE_API_URL}/api/logistics/orders/${id}/${action}`, body); if (action === "couriers") setCouriers((value) => ({ ...value, [id]: data.couriers || [] })); if (data.labelUrl) window.open(data.labelUrl, "_blank", "noopener,noreferrer"); toast.success(success); await loadOrders(); }
    catch (error) { toast.error(error.response?.data?.message || "Shiprocket operation failed"); }
    finally { setShippingBusy((value) => ({ ...value, [id]: "" })); }
  };
  const confirmedShippingAction = (order, action, body, success, prompt) => { if (window.confirm(prompt)) shippingAction(order, action, body, success); };

  return <SellerPage><SellerHeader title="Orders" description="Confirm, fulfil, track, return and refund customer orders." />
    <div className="mb-6 flex flex-col gap-3 rounded-2xl border border-slate-200 bg-white p-4 shadow-sm md:flex-row"><label className="relative flex-1"><FiSearch className="absolute left-4 top-1/2 -translate-y-1/2 text-slate-400"/><input className="field-control pl-11" value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search order, customer, phone, email or AWB" /></label><select className="field-control md:w-64" value={status} onChange={(event) => setStatus(event.target.value)}>{statuses.map((item) => <option key={item}>{item}</option>)}</select></div>
    <section className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="border-b px-6 py-5"><h2 className="font-semibold">All orders</h2><p className="mt-1 text-sm text-slate-500">{loading ? "Loading…" : `${filtered.length} results`}</p></div>
      {!loading && !filtered.length ? <SellerEmpty title="No matching orders" description="Try changing the search or status filter." /> : <div className="divide-y">{filtered.map((order) => { const id = String(order._id); const draft = drafts[id] || {}; const courierOptions = rankCouriers(couriers[id]); const recommendedCourierId = courierOptions[0]?.courier_company_id; const selectedCourier = courierOptions.find((item) => String(item.courier_company_id) === String(draft.courierChoice)); return <article key={id}>
        <button type="button" onClick={() => setExpanded(expanded === id ? null : id)} className="grid w-full gap-4 px-6 py-5 text-left hover:bg-slate-50 md:grid-cols-[1fr_1.2fr_1fr_.7fr_.7fr] md:items-center"><div><p className="font-mono text-xs font-semibold">#{id.slice(-8).toUpperCase()}</p><p className="mt-1 text-xs text-slate-400">{new Date(order.createdAt).toLocaleDateString("en-IN")}</p></div><div><p className="font-semibold">{order.customerName}</p><a href={`tel:${order.phone}`} onClick={(event) => event.stopPropagation()} className="text-xs text-brand-primary">{order.phone}</a></div><StatusBadge value={order.status}/><p className="text-sm text-slate-500">{order.paymentMethod}</p><p className="font-bold md:text-right">₹{Number(order.totalAmount).toLocaleString("en-IN")}</p></button>
        {expanded === id && <div className="border-t bg-slate-50/70 p-6"><div className="grid gap-6 xl:grid-cols-[1fr_360px]"><div><h3 className="field-label">Items</h3><div className="space-y-3">{order.products.map((item, index) => <div key={`${item.sku}-${index}`} className="flex gap-4 rounded-xl border bg-white p-3"><img src={item.image || "/placeholder.png"} alt="" className="h-16 w-14 rounded-lg object-cover"/><div className="min-w-0 flex-1"><p className="font-medium">{item.name}</p><p className="text-xs text-slate-500">{item.selectedColor} · {item.selectedSize} · SKU {item.sku || "—"} · Qty {item.qty}</p></div><p className="font-semibold">₹{item.price * item.qty}</p></div>)}</div>
          <div className="mt-5 grid gap-4 rounded-xl border bg-white p-4 text-sm sm:grid-cols-2"><div><p className="font-semibold">Delivery address</p><p className="mt-1 text-slate-600">{order.address}<br/>{order.city} - {order.pincode}<br/>{order.email}</p></div><div><p className="font-semibold">Timeline</p><div className="mt-2 space-y-2">{(order.statusHistory || []).map((item, index) => <div key={`${item.status}-${index}`}><p className="font-medium">{item.status}</p><p className="text-xs text-slate-500">{item.note} · {new Date(item.createdAt).toLocaleString("en-IN")}</p></div>)}</div></div></div>
          {order.internalNotes?.length > 0 && <div className="mt-4 rounded-xl border border-amber-200 bg-amber-50 p-4"><p className="font-semibold">Internal notes</p>{order.internalNotes.map((item, index) => <p key={index} className="mt-2 text-sm">{item.note} <span className="text-xs text-slate-500">— {item.createdBy}</span></p>)}</div>}</div>
          <aside className="space-y-4"><section className="rounded-xl border bg-white p-4"><p className="font-semibold">Next action</p><select value="" onChange={(event) => event.target.value && updateOrder(id, { status: event.target.value }, `Order moved to ${event.target.value}`)} className="field-control mt-3"><option value="">Choose status…</option>{(nextStatuses[order.status] || []).map((item) => <option key={item}>{item}</option>)}</select></section>
            <section className="rounded-xl border bg-white p-4"><div className="flex items-center justify-between gap-3"><p className="flex items-center gap-2 font-semibold"><FiTruck/> Shiprocket</p>{order.shipping?.externalOrderId && <span className="rounded-full bg-emerald-50 px-2 py-1 text-xs font-semibold text-emerald-700">Connected</span>}</div><p className="mt-1 text-xs text-slate-500">Confirm the order and verify package details before creating a shipment.</p>
              <div className="mt-3 rounded-lg bg-slate-50 p-3 text-xs text-slate-600"><span className="font-semibold">Verified destination:</span> {order.city}{order.state ? `, ${order.state}` : " · State will be verified from the pincode"} · {order.pincode}</div>
              <div className="mt-2 grid grid-cols-2 gap-2">{[["weight", "Weight kg", 0.1, 0.5], ["length", "Length cm", 0.5, 15], ["breadth", "Breadth cm", 0.5, 12], ["height", "Height cm", 0.5, 5]].map(([key, label, step, fallback]) => <label key={key} className="text-xs text-slate-500">{label}<input type="number" min={step} step={step} value={draft[key] ?? order.shipping?.package?.[key] ?? fallback} onChange={(event) => changeDraft(id, key, event.target.value)} className="field-control mt-1"/></label>)}</div>
              {!order.shipping?.externalOrderId ? <button disabled={Boolean(shippingBusy[id])} onClick={() => confirmedShippingAction(order, "create", parcelBody(order, draft), "Shipment created in Shiprocket", "Create this order in Shiprocket using the displayed address and package details?")} className="btn-primary mt-3 w-full">{shippingBusy[id] === "create" ? "Creating…" : "Create shipment"}</button> : <>
                <button disabled={Boolean(shippingBusy[id])} onClick={() => shippingAction(order, "couriers", parcelBody(order, draft), "Courier options loaded")} className="btn-secondary mt-3 w-full">Check available couriers</button>
                {courierOptions.length > 0 && <div className="mt-3 space-y-2"><div className="flex items-center justify-between"><p className="text-xs font-semibold uppercase tracking-wide text-slate-500">{courierOptions.length} courier options</p><p className="text-xs text-slate-500">Select one to continue</p></div>{courierOptions.map((item) => { const selected = String(item.courier_company_id) === String(draft.courierChoice); const recommended = String(item.courier_company_id) === String(recommendedCourierId); return <button type="button" key={item.courier_company_id} onClick={() => changeDraft(id, "courierChoice", String(item.courier_company_id))} className={`relative w-full rounded-xl border p-3 text-left transition ${selected ? "border-brand-primary bg-emerald-50 ring-2 ring-emerald-100" : recommended ? "border-amber-300 bg-amber-50/60 hover:border-amber-400" : "border-slate-200 hover:border-slate-300 hover:bg-slate-50"}`}>{recommended && <span className="mb-3 inline-flex rounded-full bg-amber-100 px-2.5 py-1 text-[11px] font-bold uppercase tracking-wide text-amber-800">Recommended · Best value</span>}<div className="flex items-start justify-between gap-3"><div><p className="text-sm font-semibold text-slate-900">{item.courier_name}</p><p className="mt-1 text-xs text-slate-500">{item.is_surface ? "Surface" : item.mode || "Courier"} · Rating {courierMetric(item.rating)}</p></div><p className="text-base font-bold text-brand-primary">{money(item.rate)}</p></div><div className="mt-3 grid grid-cols-2 gap-x-3 gap-y-2 border-t border-slate-200 pt-3 text-xs sm:grid-cols-3"><div><span className="block text-slate-400">Chargeable weight</span><strong>{courierMetric(item.charge_weight ?? item.min_weight ?? item.weight, " kg")}</strong></div><div><span className="block text-slate-400">RTO charge</span><strong>{money(item.rto_charges)}</strong></div><div><span className="block text-slate-400">Delivery estimate</span><strong>{courierMetric(item.etd || item.estimated_delivery_days)}</strong></div><div><span className="block text-slate-400">Pickup</span><strong>{courierMetric(item.pickup_availability === "1" || item.pickup_availability === 1 ? "Available" : item.pickup_availability)}</strong></div><div><span className="block text-slate-400">COD charge</span><strong>{money(item.cod_charges)}</strong></div><div><span className="block text-slate-400">Freight</span><strong>{money(item.freight_charge ?? item.rate)}</strong></div></div></button>; })}</div>}
                {!order.shipping?.awbCode && <button disabled={!selectedCourier || Boolean(shippingBusy[id])} onClick={() => confirmedShippingAction(order, "awb", { courierId: selectedCourier.courier_company_id, courierName: selectedCourier.courier_name }, "AWB assigned", `Assign ${selectedCourier?.courier_name || "this courier"}? Shiprocket may debit the shipping charge from your wallet.`)} className="btn-primary mt-3 w-full">{selectedCourier ? `Assign ${selectedCourier.courier_name} · ${money(selectedCourier.rate)}` : "Select a courier to assign"}</button>}
                {order.shipping?.awbCode && <div className="mt-3 rounded-lg bg-slate-50 p-3 text-xs"><p><strong>{order.shipping.courierName}</strong></p><p className="mt-1 font-mono">AWB {order.shipping.awbCode}</p></div>}
                {order.shipping?.awbCode && !order.shipping?.pickupScheduled && <button disabled={Boolean(shippingBusy[id])} onClick={() => confirmedShippingAction(order, "pickup", {}, "Pickup scheduled", "The parcel must be packed, labelled and ready. Schedule courier pickup now?")} className="btn-primary mt-2 w-full">Schedule pickup</button>}
                {order.shipping?.awbCode && <button disabled={Boolean(shippingBusy[id])} onClick={() => shippingAction(order, "label", {}, "Label generated")} className="btn-secondary mt-2 w-full"><FiDownload/> {order.shipping?.labelUrl ? "Open label" : "Generate label"}</button>}
                {order.shipping?.awbCode && !order.shipping?.pickupScheduled && order.shipping?.externalStatus !== "Shipment cancelled" && <button disabled={Boolean(shippingBusy[id])} onClick={() => confirmedShippingAction(order, "cancel", {}, "Shiprocket shipment cancelled", "Cancel the assigned AWB? This does not cancel the customer order or restore stock.")} className="mt-2 w-full rounded-xl border border-red-200 px-4 py-3 font-semibold text-red-700 hover:bg-red-50">Cancel shipment</button>}
              </>}{order.shipping?.externalStatus && <p className="mt-2 text-xs text-slate-500">Latest courier update: {order.shipping.externalStatus}</p>}</section>
            <section className="rounded-xl border bg-white p-4"><p className="font-semibold">Manual tracking</p><input value={draft.courier ?? order.tracking?.courier ?? ""} onChange={(event) => changeDraft(id, "courier", event.target.value)} placeholder="Courier name" className="field-control mt-3"/><input value={draft.trackingId ?? order.tracking?.trackingId ?? ""} onChange={(event) => changeDraft(id, "trackingId", event.target.value)} placeholder="AWB / tracking number" className="field-control mt-2"/><button onClick={() => updateOrder(id, { tracking: { courier: draft.courier ?? order.tracking?.courier, trackingId: draft.trackingId ?? order.tracking?.trackingId } }, "Tracking saved")} className="btn-secondary mt-2 w-full">Save manual tracking</button></section>
            <section className="rounded-xl border bg-white p-4"><p className="font-semibold">Internal note</p><textarea rows="3" value={draft.note || ""} onChange={(event) => changeDraft(id, "note", event.target.value)} className="field-control mt-3" placeholder="Visible only to staff"/><button onClick={() => updateOrder(id, { internalNote: draft.note }, "Note added")} className="btn-secondary mt-2 w-full">Add note</button></section><div className="grid grid-cols-2 gap-2"><button onClick={() => download(id, "invoice")} className="btn-secondary"><FiDownload/> Invoice</button><button onClick={() => download(id, "packing-slip")} className="btn-secondary"><FiPackage/> Pack slip</button></div><button onClick={() => resend(id)} className="btn-secondary w-full"><FiMail/> Email invoice</button></aside>
        </div></div>}
      </article>; })}</div>}
    </section></SellerPage>;
}

export default AdminOrders;
