import { useEffect, useState } from "react";
import axios from "axios";
import toast from "react-hot-toast";
import { FiChevronDown, FiCopy, FiCreditCard, FiDownload, FiPackage, FiRotateCcw, FiStar, FiTruck, FiX } from "react-icons/fi";
import { Link } from "react-router-dom";
import PageLoader from "../components/PageLoader";

const forwardSteps = ["Pending", "Confirmed", "Packed", "Shipped", "Delivered"];
const terminalStatuses = new Set(["Cancelled", "Refunded", "RTO Delivered"]);
const noCodCollectionStatuses = new Set(["Cancelled", "RTO Initiated", "RTO Delivered"]);
const money = (value) => `₹${Number(value || 0).toLocaleString("en-IN", { maximumFractionDigits: 2 })}`;
const paymentLabel = (order) => {
  if (order.paymentMethod !== "COD") return order.paymentStatus === "Refunded" ? "Online payment · Refunded" : "Paid online";
  if (noCodCollectionStatuses.has(order.status)) return "Cash on delivery · No payment collected";
  if (order.status === "Refunded" || order.paymentStatus === "Refunded") return "Cash on delivery · Refunded";
  if (["Delivered", "Return Requested", "Return Approved", "Return Picked Up", "Returned", "Refund Pending"].includes(order.status)) return "Cash collected on delivery";
  return "Cash on delivery · Payment pending";
};

function Progress({ status }) {
  const currentIndex = forwardSteps.indexOf(status);
  if (currentIndex < 0) return null;
  return <div className="mt-6 rounded-2xl bg-slate-50 px-4 py-5 sm:px-6"><div className="relative grid grid-cols-5"><div className="absolute left-[10%] right-[10%] top-3 h-1 rounded-full bg-slate-200"><span className="block h-full rounded-full bg-brand-primary transition-all" style={{ width: `${(currentIndex / (forwardSteps.length - 1)) * 100}%` }}/></div>{forwardSteps.map((step, index) => <div key={step} className="relative z-10 flex min-w-0 flex-col items-center"><span className={`grid h-7 w-7 place-items-center rounded-full border-2 text-[10px] font-bold ${index <= currentIndex ? "border-brand-primary bg-brand-primary text-white" : "border-slate-200 bg-white text-slate-400"}`}>{index + 1}</span><span className={`mt-2 max-w-full truncate text-[10px] font-semibold sm:text-xs ${index <= currentIndex ? "text-brand-primary" : "text-slate-400"}`}>{step}</span></div>)}</div></div>;
}

function ShippingDetails({ order, delivered, closed }) {
  const awb = order.tracking?.trackingId;
  const copyAwb = async () => { try { await navigator.clipboard.writeText(awb); toast.success("AWB copied"); } catch { toast.error("Could not copy AWB"); } };
  return <section className="rounded-2xl border bg-slate-50 p-4"><div className="flex items-center gap-2 font-semibold"><FiTruck/> {closed ? "Shipment record" : "Shipping details"}</div>{closed && <p className="mt-1 text-xs text-slate-500">This shipment is closed. Details are retained for reference.</p>}{awb ? <><dl className="mt-4 space-y-3"><div><dt className="text-[11px] font-bold uppercase tracking-wide text-slate-400">Courier partner</dt><dd className="mt-1 text-sm font-semibold text-slate-800">{order.tracking.courier || "Courier partner"}</dd></div><div><dt className="text-[11px] font-bold uppercase tracking-wide text-slate-400">AWB / tracking number</dt><dd className="mt-1 flex items-center justify-between gap-2 rounded-xl border bg-white px-3 py-2"><span className="break-all font-mono text-sm font-bold text-brand-primary">{awb}</span><button type="button" onClick={copyAwb} aria-label="Copy AWB number" className="grid h-8 w-8 shrink-0 place-items-center rounded-lg text-slate-500 hover:bg-slate-100"><FiCopy/></button></dd></div></dl><a href={`https://www.shiprocket.in/shipment-tracking/?tracking_id=${awb}`} target="_blank" rel="noreferrer" className={`${closed ? "btn-secondary" : "btn-primary"} mt-4 w-full text-sm`}>{closed ? "View shipment history" : "Track package"}</a></> : <p className="mt-3 text-sm text-slate-500">{delivered || closed ? "This order was completed without an online tracking number." : "Tracking appears after dispatch."}</p>}</section>;
}

export default function MyOrders() {
  const [orders, setOrders] = useState([]);
  const [loading, setLoading] = useState(true);
  const [returnOrder, setReturnOrder] = useState(null);
  const [returnReason, setReturnReason] = useState("");
  const [returnImages, setReturnImages] = useState([]);
  const [returning, setReturning] = useState(false);
  const [reviewItem, setReviewItem] = useState(null);
  const [reviewRating, setReviewRating] = useState(5);
  const [reviewComment, setReviewComment] = useState("");
  const [reviewing, setReviewing] = useState(false);

  const loadOrders = async () => { try { const { data } = await axios.get(`${import.meta.env.VITE_API_URL}/api/orders/my-orders`); setOrders(data); } catch { toast.error("Could not load your orders"); } finally { setLoading(false); } };
  useEffect(() => { window.scrollTo({ top: 0, behavior: "instant" }); let active = true; axios.get(`${import.meta.env.VITE_API_URL}/api/orders/my-orders`).then(({ data }) => { if (active) setOrders(data); }).catch(() => { if (active) toast.error("Could not load your orders"); }).finally(() => { if (active) setLoading(false); }); return () => { active = false; }; }, []);

  const downloadInvoice = async (id) => { try { const response = await axios.get(`${import.meta.env.VITE_API_URL}/api/orders/invoice/${id}`, { responseType: "blob" }); const url = URL.createObjectURL(response.data); const link = document.createElement("a"); link.href = url; link.download = `invoice-${id}.pdf`; link.click(); URL.revokeObjectURL(url); } catch { toast.error("Invoice download failed"); } };
  const cancel = async (id) => { const reason = window.prompt("Why would you like to cancel this order?"); if (reason === null) return; try { const { data } = await axios.put(`${import.meta.env.VITE_API_URL}/api/orders/cancel/${id}`, { reason }); toast.success(data.message); loadOrders(); } catch (error) { toast.error(error.response?.data?.message || "Cancellation failed"); } };
  const requestReturn = async (event) => { event.preventDefault(); if (returnReason.trim().length < 10) return toast.error("Please explain the return reason in a little more detail"); const data = new FormData(); data.append("reason", returnReason.trim()); returnImages.forEach((file) => data.append("images", file)); setReturning(true); try { await axios.post(`${import.meta.env.VITE_API_URL}/api/orders/return/${returnOrder._id}`, data); toast.success("Return request submitted for review"); setReturnOrder(null); setReturnReason(""); setReturnImages([]); await loadOrders(); } catch (error) { toast.error(error.response?.data?.message || "Return request failed"); } finally { setReturning(false); } };
  const openReview = async (item) => { try { const { data } = await axios.get(`${import.meta.env.VITE_API_URL}/api/products/${item._id}/review-eligibility`); if (!data.eligible) return toast.error(data.reason || "This product cannot be reviewed yet"); setReviewItem(item); setReviewRating(5); setReviewComment(""); } catch (error) { toast.error(error.response?.data?.message || "Review eligibility could not be checked"); } };
  const submitReview = async (event) => { event.preventDefault(); if (reviewComment.trim().length < 5) return toast.error("Please write a little more about the product"); setReviewing(true); try { const { data } = await axios.post(`${import.meta.env.VITE_API_URL}/api/products/${reviewItem._id}/review`, { rating: reviewRating, comment: reviewComment.trim() }); toast.success(data.message || "Review submitted for approval"); setReviewItem(null); } catch (error) { toast.error(error.response?.data?.message || "Review could not be submitted"); } finally { setReviewing(false); } };

  if (loading) return <PageLoader title="Loading your orders" message="We’re retrieving your purchases and tracking updates." />;
  return <main className="mx-auto w-full max-w-7xl px-4 py-8 sm:px-6 md:py-12 lg:px-8"><header className="mb-7 md:mb-10"><p className="eyebrow">Your account</p><h1 className="mt-2 text-3xl font-bold tracking-tight sm:text-4xl">Orders and tracking</h1><p className="mt-2 text-sm text-slate-500 sm:text-base">Track deliveries, download invoices, request returns and review delivered products.</p></header>
    {!orders.length ? <section className="surface-card px-6 py-20 text-center"><FiPackage className="mx-auto text-4xl text-brand-primary"/><h2 className="mt-4 text-xl font-semibold">No orders yet</h2><p className="mt-2 text-slate-500">Your purchases will appear here.</p></section> : <div className="space-y-6">{orders.map((order) => { const isException = !forwardSteps.includes(order.status); const delivered = order.status === "Delivered"; const isCod = order.paymentMethod === "COD"; return <article key={order._id} className="overflow-hidden rounded-3xl border border-slate-200 bg-white shadow-sm"><header className="flex flex-wrap items-center justify-between gap-4 border-b border-slate-200 bg-slate-50/70 px-4 py-4 sm:px-6"><div><p className="font-mono text-xs font-bold tracking-wide text-slate-600">ORDER #{String(order._id).slice(-8).toUpperCase()}</p><p className="mt-1 text-xs text-slate-500">Placed {new Date(order.createdAt).toLocaleDateString("en-IN", { day: "numeric", month: "short", year: "numeric" })}</p><p className={`mt-2 inline-flex items-center gap-1.5 rounded-full px-2.5 py-1 text-xs font-semibold ${isCod ? "bg-amber-50 text-amber-800" : "bg-blue-50 text-blue-700"}`}>{isCod ? <FiPackage/> : <FiCreditCard/>}{paymentLabel(order)}</p></div><div className="flex items-center gap-4"><span className={`inline-flex rounded-full px-3 py-1 text-xs font-semibold ${terminalStatuses.has(order.status) ? "bg-red-50 text-red-700" : isException ? "bg-amber-50 text-amber-700" : "bg-emerald-50 text-emerald-700"}`}>{order.status}</span><p className="text-lg font-bold sm:text-xl">{money(order.totalAmount)}</p></div></header>
        <div className="grid gap-6 p-4 sm:p-6 lg:grid-cols-[minmax(0,1fr)_280px]">
          <div className="min-w-0"><div className="space-y-3">{order.products.map((item, index) => <div key={`${item.sku || item._id}-${index}`} className="rounded-2xl border border-slate-200 p-3 sm:p-4"><div className="flex items-center gap-3 sm:gap-4"><img src={item.image || "/placeholder.png"} alt={item.name} className="h-20 w-16 shrink-0 rounded-xl bg-slate-100 object-cover sm:h-24 sm:w-20"/><div className="min-w-0 flex-1"><h2 className="line-clamp-2 text-sm font-semibold sm:text-base">{item.name}</h2><p className="mt-1 text-xs text-slate-500 sm:text-sm">{item.selectedColor ? `${item.selectedColor} · ` : ""}Size {item.selectedSize} · Qty {item.qty}</p><p className="mt-2 font-bold text-brand-primary">{money(Number(item.price) * Number(item.qty))}</p></div></div>{delivered && <button type="button" onClick={() => openReview(item)} className="mt-3 inline-flex w-full items-center justify-center gap-2 rounded-xl bg-amber-50 px-4 py-2.5 text-sm font-semibold text-amber-800 hover:bg-amber-100 sm:ml-[6rem] sm:w-auto"><FiStar/> Write a review</button>}</div>)}</div>
            <Progress status={order.status}/>
            <details open={terminalStatuses.has(order.status)} className="group mt-6 rounded-2xl border border-slate-200"><summary className="flex cursor-pointer list-none items-center justify-between px-4 py-4 font-semibold"><span>Order activity <span className="ml-2 text-xs font-normal text-slate-400">{order.statusHistory?.length || 0} updates</span></span><FiChevronDown className="transition group-open:rotate-180"/></summary><div className="border-t px-5 py-5"><div className="space-y-5 border-l-2 border-slate-200 pl-5">{[...(order.statusHistory || [])].reverse().map((item, index) => <div key={`${item.status}-${index}`} className="relative"><span className="absolute -left-[1.63rem] top-1 h-3 w-3 rounded-full bg-brand-primary ring-4 ring-white"/><div className="flex flex-wrap items-baseline justify-between gap-2"><p className="text-sm font-semibold">{item.status}</p><time className="text-[11px] text-slate-400">{new Date(item.createdAt).toLocaleString("en-IN")}</time></div><p className="mt-1 text-xs text-slate-500">{item.note || "Order updated"}</p></div>)}</div></div></details>
          </div>
          <aside className="space-y-3 lg:border-l lg:border-slate-200 lg:pl-6"><ShippingDetails order={order} delivered={delivered} closed={terminalStatuses.has(order.status)}/><button type="button" onClick={() => downloadInvoice(order._id)} className="btn-secondary w-full"><FiDownload/> Download invoice</button>{["Pending", "Confirmed"].includes(order.status) && <button type="button" onClick={() => cancel(order._id)} className="w-full rounded-xl border border-red-200 bg-red-50 px-4 py-3 font-semibold text-red-700">Cancel order</button>}{delivered && <button type="button" onClick={() => { setReturnOrder(order); setReturnReason(""); setReturnImages([]); }} className="btn-secondary w-full"><FiRotateCcw/> Request return</button>}<Link to={`/contact?topic=order&order=${encodeURIComponent(String(order._id).slice(-8).toUpperCase())}`} className="block text-center text-sm font-semibold text-brand-primary hover:underline">Need help with this order?</Link>{order.returnRequest?.reason && <div className="rounded-xl bg-amber-50 p-4 text-sm"><div className="flex items-center justify-between gap-2"><p className="font-semibold text-amber-900">{order.status === "Refunded" ? "Return completed" : "Return request"}</p>{order.status !== "Refunded" && order.returnRequest.reviewStatus && <span className="rounded-full bg-white px-2 py-1 text-xs font-semibold text-amber-800">{order.returnRequest.reviewStatus}</span>}</div><p className="mt-2 text-amber-800">{order.returnRequest.reason}</p>{order.returnRequest.adminNote && <p className="mt-2 border-t border-amber-200 pt-2 text-amber-900">Seller response: {order.returnRequest.adminNote}</p>}</div>}{order.refund?.status && <div className="rounded-xl bg-violet-50 p-4 text-sm"><p className="font-semibold text-violet-900">{order.status === "Refunded" ? "Refund completed" : `Refund ${order.refund.status}`}</p><p className="mt-2"><span className="text-violet-600">Amount:</span> <strong className="text-violet-900">{money(order.refund.amount)}</strong></p>{order.refund.method && <p className="mt-1 text-violet-800"><span className="text-violet-600">Paid via:</span> {order.refund.method}</p>}{order.refund.reference && <p className="mt-1 break-all text-violet-800"><span className="text-violet-600">Reference:</span> <span className="font-mono text-xs">{order.refund.reference}</span></p>}</div>}</aside>
        </div></article>; })}</div>}

    {reviewItem && <div className="fixed inset-0 z-[70] grid place-items-center overflow-y-auto bg-slate-950/55 p-4" onMouseDown={(event) => { if (event.target === event.currentTarget && !reviewing) setReviewItem(null); }}><form onSubmit={submitReview} className="my-auto w-full max-w-lg rounded-3xl bg-white p-6 shadow-2xl md:p-8"><div className="flex items-start justify-between gap-4"><div><p className="eyebrow">Verified purchase</p><h2 className="mt-2 text-2xl font-bold">Review this product</h2></div><button type="button" onClick={() => setReviewItem(null)} aria-label="Close review form" className="grid h-10 w-10 place-items-center rounded-full bg-slate-100"><FiX/></button></div><div className="mt-5 flex items-center gap-3 rounded-2xl bg-slate-50 p-3"><img src={reviewItem.image || "/placeholder.png"} alt="" className="h-16 w-14 rounded-lg object-cover"/><p className="line-clamp-2 text-sm font-semibold">{reviewItem.name}</p></div><fieldset className="mt-6"><legend className="text-sm font-semibold">Your rating</legend><div className="mt-3 flex gap-2">{[1,2,3,4,5].map((value) => <button key={value} type="button" onClick={() => setReviewRating(value)} aria-label={`${value} star${value > 1 ? "s" : ""}`} className={`grid h-11 w-11 place-items-center rounded-xl text-xl ${value <= reviewRating ? "bg-amber-100 text-amber-600" : "bg-slate-100 text-slate-400"}`}><FiStar fill={value <= reviewRating ? "currentColor" : "none"}/></button>)}</div></fieldset><label className="mt-5 block text-sm font-semibold">Your experience<textarea required minLength="5" maxLength="1000" rows="5" value={reviewComment} onChange={(event) => setReviewComment(event.target.value)} className="field-control mt-2" placeholder="Tell other parents about quality, comfort, sizing and fit"/></label><p className="mt-2 text-xs text-slate-500">Your review will appear after seller approval.</p><div className="mt-6 grid grid-cols-2 gap-3"><button type="button" disabled={reviewing} onClick={() => setReviewItem(null)} className="btn-secondary">Cancel</button><button disabled={reviewing} className="btn-primary">{reviewing ? "Submitting…" : "Submit review"}</button></div></form></div>}
    {returnOrder && <div className="fixed inset-0 z-[70] grid place-items-center overflow-y-auto bg-slate-950/55 p-4" onMouseDown={(event) => { if (event.target === event.currentTarget && !returning) setReturnOrder(null); }}><form onSubmit={requestReturn} className="my-auto w-full max-w-lg rounded-3xl bg-white p-6 shadow-2xl md:p-8"><div className="flex items-start justify-between gap-4"><div><p className="eyebrow">After-sales support</p><h2 className="mt-2 text-2xl font-bold">Request a return</h2></div><button type="button" onClick={() => setReturnOrder(null)} aria-label="Close return form" className="grid h-10 w-10 place-items-center rounded-full bg-slate-100"><FiX/></button></div><p className="mt-3 text-sm text-slate-500">Requests are reviewed before reverse pickup or refund. Add clear photos for damaged, incorrect or incomplete items.</p><label className="mt-5 block text-sm font-semibold">Reason for return<textarea required minLength="10" maxLength="500" rows="5" value={returnReason} onChange={(event) => setReturnReason(event.target.value)} className="field-control mt-2" placeholder="Describe the issue and condition of the item"/></label><label className="mt-4 block text-sm font-semibold">Photos <span className="font-normal text-slate-400">(optional, up to 3)</span><input type="file" accept="image/jpeg,image/png,image/webp,image/avif,image/heic,image/heif" multiple onChange={(event) => { const files = [...event.target.files].slice(0, 3); if (event.target.files.length > 3) toast.error("You can upload up to 3 photos"); setReturnImages(files); }} className="mt-2 block w-full rounded-xl border bg-slate-50 p-3 text-sm"/></label>{returnImages.length > 0 && <p className="mt-2 text-xs text-slate-500">{returnImages.length} photo{returnImages.length > 1 ? "s" : ""} selected · Maximum 5 MB each</p>}<div className="mt-6 grid grid-cols-2 gap-3"><button type="button" disabled={returning} onClick={() => setReturnOrder(null)} className="btn-secondary">Cancel</button><button disabled={returning} className="btn-primary">{returning ? "Submitting…" : "Submit request"}</button></div></form></div>}
  </main>;
}
