import { useEffect, useState } from "react";
import axios from "axios";
import toast from "react-hot-toast";
import { FiDownload, FiPackage, FiTruck } from "react-icons/fi";

const forwardSteps = ["Pending", "Confirmed", "Packed", "Shipped", "Delivered"];
const terminalStatuses = new Set(["Cancelled", "Refunded", "RTO Delivered"]);

export default function MyOrders() {
  const [orders, setOrders] = useState([]); const [loading, setLoading] = useState(true);
  const loadOrders = async () => { try { const { data } = await axios.get(`${import.meta.env.VITE_API_URL}/api/orders/my-orders`); setOrders(data); } catch { toast.error("Could not load your orders"); } finally { setLoading(false); } };
  useEffect(() => { let active = true; axios.get(`${import.meta.env.VITE_API_URL}/api/orders/my-orders`).then(({ data }) => { if (active) setOrders(data); }).catch(() => { if (active) toast.error("Could not load your orders"); }).finally(() => { if (active) setLoading(false); }); return () => { active = false; }; }, []);
  const downloadInvoice = async (id) => { try { const response = await axios.get(`${import.meta.env.VITE_API_URL}/api/orders/invoice/${id}`, { responseType: "blob" }); const url = URL.createObjectURL(response.data); const link = document.createElement("a"); link.href = url; link.download = `invoice-${id}.pdf`; link.click(); URL.revokeObjectURL(url); } catch { toast.error("Invoice download failed"); } };
  const cancel = async (id) => { const reason = window.prompt("Why would you like to cancel this order?"); if (reason === null) return; try { const { data } = await axios.put(`${import.meta.env.VITE_API_URL}/api/orders/cancel/${id}`, { reason }); toast.success(data.message); loadOrders(); } catch (error) { toast.error(error.response?.data?.message || "Cancellation failed"); } };
  const requestReturn = async (id) => { const reason = window.prompt("Tell us why you want to return this order:"); if (!reason?.trim()) return; try { await axios.post(`${import.meta.env.VITE_API_URL}/api/orders/return/${id}`, { reason }); toast.success("Return requested"); loadOrders(); } catch (error) { toast.error(error.response?.data?.message || "Return request failed"); } };

  if (loading) return <div className="grid min-h-[60vh] place-items-center text-slate-500">Loading your orders…</div>;
  return <main className="mx-auto max-w-6xl px-5 py-12 md:py-16"><div className="mb-9"><p className="eyebrow">Your account</p><h1 className="mt-2 text-4xl font-bold">Orders and tracking</h1><p className="mt-2 text-slate-500">Follow every order from confirmation to delivery.</p></div>
    {!orders.length ? <section className="surface-card px-6 py-20 text-center"><FiPackage className="mx-auto text-4xl text-brand-primary"/><h2 className="mt-4 text-xl font-semibold">No orders yet</h2><p className="mt-2 text-slate-500">Your purchases will appear here.</p></section> : <div className="space-y-7">{orders.map((order) => { const currentIndex = forwardSteps.indexOf(order.status); const isException = currentIndex < 0; return <article key={order._id} className="surface-card overflow-hidden"><header className="flex flex-wrap items-center justify-between gap-4 border-b bg-slate-50/70 px-5 py-4 md:px-7"><div><p className="font-mono text-xs font-semibold text-slate-500">ORDER #{String(order._id).slice(-8).toUpperCase()}</p><p className="mt-1 text-sm text-slate-500">Placed {new Date(order.createdAt).toLocaleDateString("en-IN")}</p></div><div className="text-right"><span className={`inline-flex rounded-full px-3 py-1 text-xs font-semibold ${terminalStatuses.has(order.status) ? "bg-red-50 text-red-700" : isException ? "bg-amber-50 text-amber-700" : "bg-emerald-50 text-emerald-700"}`}>{order.status}</span><p className="mt-2 text-xl font-bold">₹{Number(order.totalAmount).toLocaleString("en-IN")}</p></div></header>
        <div className="p-5 md:p-7"><div className="grid gap-7 lg:grid-cols-[1fr_300px]"><div><div className="space-y-3">{order.products.map((item, index) => <div key={`${item.sku}-${index}`} className="flex items-center gap-4 rounded-xl border p-3"><img src={item.image || "/placeholder.png"} alt={item.name} className="h-20 w-16 rounded-lg object-cover"/><div className="min-w-0 flex-1"><h2 className="font-semibold">{item.name}</h2><p className="mt-1 text-sm text-slate-500">{item.selectedColor && `${item.selectedColor} · `}Size {item.selectedSize} · Qty {item.qty}</p></div><p className="font-semibold">₹{Number(item.price * item.qty).toLocaleString("en-IN")}</p></div>)}</div>
          {!isException && <div className="mt-7"><div className="flex justify-between">{forwardSteps.map((step, index) => <div key={step} className="flex flex-1 flex-col items-center text-center"><span className={`grid h-7 w-7 place-items-center rounded-full text-xs font-bold ${index <= currentIndex ? "bg-brand-primary text-white" : "bg-slate-200 text-slate-500"}`}>{index + 1}</span><span className="mt-2 hidden text-xs font-medium sm:block">{step}</span></div>)}</div><div className="mx-[10%] -mt-[2.55rem] flex">{forwardSteps.slice(1).map((step, index) => <span key={step} className={`h-1 flex-1 ${index < currentIndex ? "bg-brand-primary" : "bg-slate-200"}`}/>)}</div></div>}
          <div className="mt-8 border-t pt-5"><h3 className="font-semibold">Activity</h3><div className="mt-3 space-y-4 border-l-2 border-slate-200 pl-5">{[...(order.statusHistory || [])].reverse().map((item, index) => <div key={`${item.status}-${index}`} className="relative"><span className="absolute -left-[1.65rem] top-1 h-3 w-3 rounded-full bg-brand-primary ring-4 ring-white"/><p className="font-medium">{item.status}</p><p className="text-sm text-slate-500">{item.note || "Order updated"}</p><time className="text-xs text-slate-400">{new Date(item.createdAt).toLocaleString("en-IN")}</time></div>)}</div></div></div>
          <aside className="space-y-4"><section className="rounded-xl border bg-slate-50 p-4"><div className="flex items-center gap-2 font-semibold"><FiTruck/> Shipping</div>{order.tracking?.trackingId ? <><p className="mt-3 text-sm">{order.tracking.courier || "Courier partner"}</p><p className="mt-1 break-all font-mono text-sm text-brand-primary">{order.tracking.trackingId}</p><a href={`https://www.shiprocket.in/shipment-tracking/?tracking_id=${order.tracking.trackingId}`} target="_blank" rel="noreferrer" className="btn-primary mt-3 w-full text-sm">Track package</a></> : <p className="mt-3 text-sm text-slate-500">Tracking appears after dispatch.</p>}</section><button onClick={() => downloadInvoice(order._id)} className="btn-secondary w-full"><FiDownload/> Download invoice</button>{["Pending", "Confirmed"].includes(order.status) && <button onClick={() => cancel(order._id)} className="w-full rounded-xl border border-red-200 bg-red-50 px-4 py-3 font-semibold text-red-700">Cancel order</button>}{order.status === "Delivered" && <button onClick={() => requestReturn(order._id)} className="btn-secondary w-full">Request return</button>}{order.returnRequest?.reason && <div className="rounded-xl bg-amber-50 p-4 text-sm"><p className="font-semibold text-amber-900">Return reason</p><p className="mt-1 text-amber-800">{order.returnRequest.reason}</p></div>}</aside></div></div></article>; })}</div>}
  </main>;
}
