import { useEffect, useState } from "react";
import { useNavigate } from "react-router-dom";
import axios from "axios";
import toast from "react-hot-toast";
import { FiAlertTriangle, FiCheckCircle, FiEdit3, FiShield, FiTrash2 } from "react-icons/fi";
import { SellerHeader, SellerPage, StatusBadge } from "../components/SellerUI";

const addressComplete = (value) => Boolean(value?.line1 && value?.city && value?.state && value?.pincode);
const Address = ({ value }) => addressComplete(value) ? <>{value.line1}{value.line2 ? `, ${value.line2}` : ""}<br/>{value.city}, {value.state} {value.pincode}</> : <span className="font-medium text-amber-700">Not provided</span>;
const editableFrom = (profile = {}) => ({
  legalBusinessName: profile.legalBusinessName || "", tradeName: profile.tradeName || "", businessType: profile.businessType || "", businessPhone: profile.businessPhone || "", authorizedSignatoryName: profile.authorizedSignatoryName || "", declarationsAccepted: false,
  registeredAddressLine1: profile.registeredAddress?.line1 || "", registeredAddressLine2: profile.registeredAddress?.line2 || "", registeredAddressCity: profile.registeredAddress?.city || "", registeredAddressState: profile.registeredAddress?.state || "", registeredAddressPincode: profile.registeredAddress?.pincode || "",
  pickupSameAsRegistered: false, pickupAddressLine1: profile.pickupAddress?.line1 || "", pickupAddressLine2: profile.pickupAddress?.line2 || "", pickupAddressCity: profile.pickupAddress?.city || "", pickupAddressState: profile.pickupAddress?.state || "", pickupAddressPincode: profile.pickupAddress?.pincode || "",
});
const Input = ({ label, value, onChange, ...props }) => <label className="field-label">{label}<input {...props} value={value} onChange={onChange} className="field-control mt-2"/></label>;

function SellerAccount() {
  const navigate = useNavigate();
  const [data, setData] = useState(null); const [error, setError] = useState(""); const [editing, setEditing] = useState(false); const [form, setForm] = useState({}); const [saving, setSaving] = useState(false);
  const [closing, setClosing] = useState(false); const [showClose, setShowClose] = useState(false); const [closeForm, setCloseForm] = useState({ password: "", confirmation: "", reason: "" });
  const load = async () => { try { const { data: result } = await axios.get(`${import.meta.env.VITE_API_URL}/api/auth/seller-profile/me`); setData(result); setForm(editableFrom(result.profile)); setError(""); } catch (requestError) { setError(requestError.response?.data?.message || "Seller profile could not be loaded"); } };
  useEffect(() => {
    let active = true;
    axios.get(`${import.meta.env.VITE_API_URL}/api/auth/seller-profile/me`)
      .then(({ data: result }) => { if (active) { setData(result); setForm(editableFrom(result.profile)); setError(""); } })
      .catch((requestError) => { if (active) setError(requestError.response?.data?.message || "Seller profile could not be loaded"); });
    return () => { active = false; };
  }, []);
  const profile = data?.profile; const change = (key, value) => setForm((current) => ({ ...current, [key]: value }));
  const save = async (event) => { event.preventDefault(); setSaving(true); try { const { data: result } = await axios.put(`${import.meta.env.VITE_API_URL}/api/auth/seller-profile/me/business-details`, form); toast.success(result.message); setEditing(false); await load(); } catch (requestError) { toast.error(requestError.response?.data?.message || "Business details could not be saved"); } finally { setSaving(false); } };
  const closeAccount = async () => { if (closeForm.confirmation.trim().toUpperCase() !== "CLOSE") return toast.error("Type CLOSE to confirm"); if (!closeForm.password) return toast.error("Enter your current password"); setClosing(true); try { await axios.delete(`${import.meta.env.VITE_API_URL}/api/auth/seller-profile/me`, { data: closeForm }); localStorage.removeItem("user"); delete axios.defaults.headers.common.Authorization; toast.success("Seller account closed"); navigate("/admin-login", { replace: true }); } catch (requestError) { toast.error(requestError.response?.data?.message || "Seller account could not be closed"); setClosing(false); } };
  return <SellerPage><SellerHeader eyebrow="Account and compliance" title="My seller profile" description="Your seller identity, fulfilment address and settlement verification are kept separate from the platform administrator." action={profile && <button type="button" onClick={() => setEditing((value) => !value)} className="btn-secondary"><FiEdit3/> {editing ? "Cancel editing" : "Update business details"}</button>}/>
    {error && <div role="alert" className="rounded-2xl border border-red-200 bg-red-50 p-4 text-red-700">{error}</div>}
    {profile?.completeness && !profile.completeness.complete && <section className="mb-5 rounded-2xl border border-amber-300 bg-amber-50 p-5"><div className="flex items-start gap-3"><FiAlertTriangle className="mt-1 shrink-0 text-amber-700"/><div><h2 className="font-bold text-amber-950">Seller verification needs an update</h2><p className="mt-1 text-sm leading-6 text-amber-900">The previous approval is not considered complete until these details are supplied and reviewed: <strong>{profile.completeness.missingFields.join(", ")}</strong>.</p><button type="button" onClick={() => setEditing(true)} className="mt-3 text-sm font-bold text-amber-950 underline">Complete business details</button></div></div></section>}
    {editing && <BusinessDetails form={form} change={change} save={save} saving={saving}/>}
    {profile && <div className="grid gap-5 lg:grid-cols-2"><section className="rounded-2xl border bg-white p-6 shadow-sm"><div className="flex items-center justify-between gap-3"><h2 className="text-xl font-bold">Business identity</h2><StatusBadge value={profile.verificationStatus}/></div><dl className="mt-6 grid gap-5 text-sm sm:grid-cols-2"><Field label="Legal name" value={profile.legalBusinessName}/><Field label="Trade name" value={profile.tradeName}/><Field label="Business type" value={String(profile.businessType || "").replaceAll("_", " ")}/><Field label="GSTIN / PAN" value={`••••${profile.gstinLast4 || "—"} / ••••${profile.panLast4 || "—"}`} mono/><div className="sm:col-span-2"><dt className="text-slate-500">Registered address</dt><dd className="mt-1 leading-6"><Address value={profile.registeredAddress}/></dd></div><div className="sm:col-span-2"><dt className="text-slate-500">Pickup address</dt><dd className="mt-1 leading-6"><Address value={profile.pickupAddress}/></dd></div></dl></section>
      <section className="rounded-2xl border bg-white p-6 shadow-sm"><h2 className="text-xl font-bold">Settlement account</h2><div className="mt-6 rounded-xl bg-slate-50 p-4"><p className="text-sm text-slate-500">Account holder</p><p className="mt-1 font-semibold">{profile.bankAccountHolder || "Not provided"}</p><p className="mt-4 font-mono text-lg">•••• •••• {profile.bankAccountLast4 || "—"}</p><p className="mt-1 text-sm uppercase text-slate-500">{profile.bankAccountType || "Account type unavailable"} · IFSC ending {profile.ifscLast4 || "—"}</p></div><div className="mt-5 space-y-3 text-sm"><CheckRow label="GST check" value={profile.gstVerification?.status}/><CheckRow label="Bank ownership check" value={profile.bankVerification?.status}/></div><p className="mt-5 flex gap-2 text-xs leading-5 text-slate-500"><FiShield className="mt-0.5 shrink-0"/>Changes to GST, PAN or settlement details require a new verification review.</p></section>
      {profile.reviewNote && <section className="rounded-2xl border border-amber-200 bg-amber-50 p-5 lg:col-span-2"><p className="flex items-center gap-2 font-semibold text-amber-950"><FiCheckCircle/> Verification note</p><p className="mt-2 text-sm text-amber-900">{profile.reviewNote}</p></section>}
      <CloseAccount show={showClose} setShow={setShowClose} value={closeForm} setValue={setCloseForm} closeAccount={closeAccount} closing={closing}/>
    </div>}
  </SellerPage>;
}

const Field = ({ label, value, mono }) => <div><dt className="text-slate-500">{label}</dt><dd className={`mt-1 font-semibold capitalize ${mono ? "font-mono" : ""}`}>{value || <span className="text-amber-700">Not provided</span>}</dd></div>;
const CheckRow = ({ label, value }) => <div className="flex items-center justify-between rounded-xl border p-3"><span>{label}</span><StatusBadge value={value}/></div>;

function BusinessDetails({ form, change, save, saving }) {
  return <form onSubmit={save} className="mb-6 rounded-2xl border bg-white p-5 shadow-sm sm:p-6"><h2 className="text-xl font-bold">Business and fulfilment details</h2><p className="mt-2 text-sm text-slate-500">Saving sends these fields back for administrator review. GST, PAN or bank changes must be handled through support so encrypted identifiers are replaced safely.</p><div className="mt-5 grid gap-4 md:grid-cols-2">
    <Input required label="Legal business name" value={form.legalBusinessName || ""} onChange={(e) => change("legalBusinessName", e.target.value)}/><Input required label="Trade / storefront name" value={form.tradeName || ""} onChange={(e) => change("tradeName", e.target.value)}/><label className="field-label">Business constitution<select required value={form.businessType || ""} onChange={(e) => change("businessType", e.target.value)} className="field-control mt-2"><option value="">Select type</option>{["proprietorship","partnership","llp","private_limited","public_limited","trust","society","other"].map((value) => <option key={value} value={value}>{value.replaceAll("_", " ")}</option>)}</select></label>
    <Input required label="Business phone" value={form.businessPhone || ""} onChange={(e) => change("businessPhone", e.target.value)}/><Input required label="Authorised signatory" value={form.authorizedSignatoryName || ""} onChange={(e) => change("authorizedSignatoryName", e.target.value)}/>
    <Input required label="Registered address" value={form.registeredAddressLine1 || ""} onChange={(e) => change("registeredAddressLine1", e.target.value)}/><Input label="Registered address line 2" value={form.registeredAddressLine2 || ""} onChange={(e) => change("registeredAddressLine2", e.target.value)}/><Input required label="Registered city" value={form.registeredAddressCity || ""} onChange={(e) => change("registeredAddressCity", e.target.value)}/><Input required label="Registered state" value={form.registeredAddressState || ""} onChange={(e) => change("registeredAddressState", e.target.value)}/><Input required label="Registered pincode" inputMode="numeric" maxLength="6" value={form.registeredAddressPincode || ""} onChange={(e) => change("registeredAddressPincode", e.target.value.replace(/\D/g, ""))}/>
    <label className="flex items-center gap-3 rounded-xl bg-slate-50 p-4 text-sm md:col-span-2"><input type="checkbox" checked={form.pickupSameAsRegistered || false} onChange={(e) => change("pickupSameAsRegistered", e.target.checked)}/> Pickup address is the same as registered address</label>
    {!form.pickupSameAsRegistered && <><Input required label="Pickup address" value={form.pickupAddressLine1 || ""} onChange={(e) => change("pickupAddressLine1", e.target.value)}/><Input label="Pickup address line 2" value={form.pickupAddressLine2 || ""} onChange={(e) => change("pickupAddressLine2", e.target.value)}/><Input required label="Pickup city" value={form.pickupAddressCity || ""} onChange={(e) => change("pickupAddressCity", e.target.value)}/><Input required label="Pickup state" value={form.pickupAddressState || ""} onChange={(e) => change("pickupAddressState", e.target.value)}/><Input required label="Pickup pincode" inputMode="numeric" maxLength="6" value={form.pickupAddressPincode || ""} onChange={(e) => change("pickupAddressPincode", e.target.value.replace(/\D/g, ""))}/></>}
    <label className="flex items-start gap-3 rounded-xl border p-4 text-sm leading-6 md:col-span-2"><input required type="checkbox" checked={form.declarationsAccepted || false} onChange={(e) => change("declarationsAccepted", e.target.checked)} className="mt-1"/><span>I confirm these business, registered-address and pickup-address details are accurate and match the seller records submitted for verification.</span></label>
  </div><button disabled={saving} className="btn-primary mt-5">{saving ? "Submitting…" : "Submit for review"}</button></form>;
}

function CloseAccount({ show, setShow, value, setValue, closeAccount, closing }) {
  return <section className="rounded-2xl border border-red-200 bg-white p-6 lg:col-span-2"><div className="flex items-start gap-3"><FiTrash2 className="mt-1 shrink-0 text-red-700"/><div className="flex-1"><h2 className="font-bold">Close seller account</h2><p className="mt-1 text-sm leading-6 text-slate-500">Removes sign-in access and archives every seller listing. Completed order, invoice, audit and statutory KYC records are retained. Closure is blocked while an order, return, refund or settlement is open.</p>{!show ? <button type="button" onClick={() => setShow(true)} className="mt-4 text-sm font-bold text-red-700 underline">Start account closure</button> : <div className="mt-5 grid gap-3 rounded-xl bg-red-50 p-4 md:grid-cols-2"><input type="password" className="field-control" placeholder="Current password" value={value.password} onChange={(e) => setValue((v) => ({ ...v, password: e.target.value }))}/><input className="field-control" placeholder="Type CLOSE" value={value.confirmation} onChange={(e) => setValue((v) => ({ ...v, confirmation: e.target.value }))}/><textarea className="field-control md:col-span-2" placeholder="Reason (optional)" value={value.reason} onChange={(e) => setValue((v) => ({ ...v, reason: e.target.value }))}/><div className="flex gap-2 md:col-span-2"><button type="button" disabled={closing} onClick={closeAccount} className="rounded-xl bg-red-700 px-4 py-3 text-sm font-bold text-white disabled:opacity-50">{closing ? "Closing…" : "Permanently close account"}</button><button type="button" onClick={() => setShow(false)} className="btn-secondary">Cancel</button></div></div>}</div></div></section>;
}

export default SellerAccount;
