import { escapeHtml } from "./html.js";
import { paymentMethodLabel, paymentStatusLabel } from "./paymentPresentation.js";
import { detailBox, emailButton, emailLayout, money } from "./emailLayout.js";

const orderUrl = (order) => `${process.env.CLIENT_URL || "https://www.tamannashut.com"}/my-orders#${escapeHtml(String(order._id || ""))}`;
const itemsHtml = (order) => (order.products || []).map((item) => `<tr><td style="padding:12px 0;border-bottom:1px solid #e5e7eb"><strong style="color:#172033">${escapeHtml(item.name || "Product")}</strong><br><span style="color:#64748b;font-size:13px">${item.selectedColor ? `Colour: ${escapeHtml(item.selectedColor)} &nbsp;·&nbsp; ` : ""}Size: ${escapeHtml(item.selectedSize || "-")} &nbsp;·&nbsp; Qty: ${Number(item.qty || 0)}</span></td><td align="right" style="padding:12px 0;border-bottom:1px solid #e5e7eb;color:#172033;font-weight:700">${money(Number(item.price || 0) * Number(item.qty || 0))}</td></tr>`).join("");

export const orderEmailTemplate = (order) => {
  const cod = order.paymentMethod === "COD";
  return emailLayout({ preheader: cod ? "Your cash-on-delivery order has been placed" : "Your online payment and order are confirmed", eyebrow: "ORDER CONFIRMATION", title: cod ? "Your order has been placed" : "Payment confirmed — order received", body: `<p style="margin-top:0">Hello <strong>${escapeHtml(order.customerName || "Customer")}</strong>,</p><p>Thank you for shopping with Tamanna's Hut. ${cod ? "No payment has been collected yet; please pay when the parcel is delivered." : "Your online payment has been verified."}</p>${detailBox(`<table role="presentation" width="100%" cellspacing="0" cellpadding="0"><tr><td><strong>Order</strong><br><span style="font-size:13px">#${escapeHtml(String(order._id || "").slice(-8).toUpperCase())}</span></td><td align="right"><strong>${money(order.totalAmount)}</strong><br><span style="font-size:13px">${escapeHtml(paymentMethodLabel(order))} · ${escapeHtml(paymentStatusLabel(order))}</span></td></tr></table>`)}<table role="presentation" width="100%" cellspacing="0" cellpadding="0">${itemsHtml(order)}</table>${emailButton("View and track order", orderUrl(order))}<p style="margin-bottom:0;color:#64748b;font-size:13px">We will email you again when your order status changes.</p>` });
};

export const passwordResetEmailTemplate = (user, resetUrl) => emailLayout({ preheader: "Your secure password reset link expires in 30 minutes", eyebrow: "ACCOUNT SECURITY", title: "Reset your password", body: `<p style="margin-top:0">Hello <strong>${escapeHtml(user.name || "Customer")}</strong>,</p><p>We received a request to create a new password for your account. This private, single-use link expires in 30 minutes.</p>${emailButton("Create new password", resetUrl)}${detailBox("If you did not request this, you can safely ignore this email. Your existing password will continue to work.")}` });

export const orderStatusEmailTemplate = (order, note = "") => emailLayout({ preheader: `Order ${String(order._id || "").slice(-8).toUpperCase()} is now ${order.status}`, eyebrow: "ORDER UPDATE", title: `Your order is ${order.status}`, body: `<p style="margin-top:0">Hello <strong>${escapeHtml(order.customerName || "Customer")}</strong>,</p><p>Order <strong>#${escapeHtml(String(order._id || "").slice(-8).toUpperCase())}</strong> has moved to <strong>${escapeHtml(order.status || "Updated")}</strong>.</p>${note ? detailBox(escapeHtml(note)) : ""}${order.tracking?.trackingId ? detailBox(`<strong>Courier:</strong> ${escapeHtml(order.tracking.courier || "Courier partner")}<br><strong>AWB / tracking number:</strong> ${escapeHtml(order.tracking.trackingId)}`) : ""}${emailButton("View order timeline", orderUrl(order))}` });

export const adminNewOrderEmailTemplate = (order) => emailLayout({ eyebrow: "SELLER ALERT", title: "New order received", body: `<p>A new ${escapeHtml(paymentMethodLabel(order).toLowerCase())} order is ready for review.</p>${detailBox(`<strong>Order:</strong> #${escapeHtml(String(order._id || "").slice(-8).toUpperCase())}<br><strong>Customer:</strong> ${escapeHtml(order.customerName || "Customer")}<br><strong>Total:</strong> ${money(order.totalAmount)}<br><strong>Payment:</strong> ${escapeHtml(paymentStatusLabel(order))}`)}${emailButton("Open seller orders", `${process.env.CLIENT_URL || "https://www.tamannashut.com"}/admin/orders`)}` });

export const cartRecoveryEmailTemplate = (user, cartUrl) => emailLayout({ eyebrow: "YOUR SAVED BAG", title: "Your items are still waiting", body: `<p style="margin-top:0">Hello <strong>${escapeHtml(user.name || "Customer")}</strong>,</p><p>You saved ${Number((user.cart || []).reduce((sum, item) => sum + Number(item.qty || 0), 0))} item(s) in your bag. Stock is not reserved until checkout.</p>${emailButton("Return to your bag", cartUrl)}<p style="font-size:13px;color:#64748b">This optional reminder can be switched off from your profile.</p>` });

export const contactCustomerEmailTemplate = (name) => emailLayout({ eyebrow: "MESSAGE RECEIVED", title: "We have received your message", body: `<p style="margin-top:0">Hello <strong>${escapeHtml(name || "Customer")}</strong>,</p><p>Thank you for contacting Tamanna's Hut. Our team will review your message and reply as soon as possible.</p>${detailBox("Keep this email for reference. You can reply directly if you need to add more information.")}` });

export const contactAdminEmailTemplate = ({ name, email, message }) => emailLayout({ eyebrow: "SELLER ALERT", title: "New customer message", body: `${detailBox(`<strong>From:</strong> ${escapeHtml(name)}<br><strong>Email:</strong> ${escapeHtml(email)}`)}<p style="white-space:pre-wrap">${escapeHtml(message)}</p>` });
