import { escapeHtml } from "./html.js";
import { paymentMethodLabel, paymentStatusLabel } from "./paymentPresentation.js";
import { detailBox, emailButton, emailLayout, money } from "./emailLayout.js";
import { calculateApparelGst } from "./gst.js";

export const calculateInvoiceTotals = calculateApparelGst;

export const invoiceTemplate = (order) => {
  const totals = calculateInvoiceTotals(order);
  const invoiceNo = order.invoiceNumber || `TH-${new Date(order.createdAt).getFullYear()}-${String(order._id).slice(-6).toUpperCase()}`;
  const rows = totals.lines.map((item) => `<tr><td style="padding:12px 0;border-bottom:1px solid #e5e7eb"><strong>${escapeHtml(item.name || "Product")}</strong><br><span style="color:#64748b;font-size:12px">${item.selectedColor ? `${escapeHtml(item.selectedColor)} · ` : ""}${escapeHtml(item.selectedSize || "-")} · Qty ${Number(item.qty || 0)} · GST ${item.rate}%${item.hsnCode ? ` · HSN ${escapeHtml(item.hsnCode)}` : ""}</span></td><td align="right" style="padding:12px 0;border-bottom:1px solid #e5e7eb">${money(item.inclusiveValue)}</td></tr>`).join("");
  const taxRows = totals.intraState ? `<tr><td style="padding-top:7px">CGST</td><td align="right" style="padding-top:7px">${money(totals.cgst)}</td></tr><tr><td style="padding-top:7px">SGST</td><td align="right" style="padding-top:7px">${money(totals.sgst)}</td></tr>` : `<tr><td style="padding-top:7px">IGST</td><td align="right" style="padding-top:7px">${money(totals.igst)}</td></tr>`;
  return emailLayout({ eyebrow: "TAX INVOICE", title: `Invoice ${invoiceNo}`, preheader: `Invoice for order ${String(order._id).slice(-8).toUpperCase()}`, body: `<p style="margin-top:0">A copy of your order invoice is below. You can also download the print-ready PDF from your order page.</p>${detailBox(`<strong>Bill to</strong><br>${escapeHtml(order.customerName || "Customer")}<br>${escapeHtml(order.address || "")}<br>${escapeHtml(order.city || "")} ${escapeHtml(order.pincode || "")}<br>${escapeHtml(order.email || "")}<br><strong>Place of supply:</strong> ${escapeHtml(totals.destinationState)}`)}<table role="presentation" width="100%" cellspacing="0" cellpadding="0">${rows}</table><table role="presentation" width="100%" cellspacing="0" cellpadding="0" style="margin-top:18px"><tr><td>Item subtotal</td><td align="right">${money(totals.itemSubtotal)}</td></tr>${totals.discount ? `<tr><td style="padding-top:7px">Discount</td><td align="right" style="padding-top:7px;color:#397153">− ${money(totals.discount)}</td></tr>` : ""}<tr><td style="padding-top:7px">Taxable value</td><td align="right" style="padding-top:7px">${money(totals.taxable)}</td></tr>${taxRows}<tr><td style="padding-top:12px;font-size:18px;font-weight:700;color:#172033">Total</td><td align="right" style="padding-top:12px;font-size:18px;font-weight:700;color:#172033">${money(totals.total)}</td></tr></table>${detailBox(`<strong>Payment method:</strong> ${escapeHtml(paymentMethodLabel(order))}<br><strong>Payment status:</strong> ${escapeHtml(paymentStatusLabel(order))}`)}${emailButton("Open your orders", `${process.env.CLIENT_URL || "https://www.tamannashut.com"}/my-orders`)}` });
};
