import mongoose from "mongoose";

const sellerProfileSchema = new mongoose.Schema({
  userId: { type: mongoose.Schema.Types.ObjectId, ref: "User", required: true, unique: true, index: true },
  legalBusinessName: { type: String, required: true, trim: true, maxlength: 120 },
  tradeName: { type: String, default: "", trim: true, maxlength: 120 },
  businessType: { type: String, enum: ["proprietorship", "partnership", "llp", "private_limited", "public_limited", "trust", "society", "other"], default: "proprietorship" },
  businessPhone: { type: String, default: "", trim: true },
  authorizedSignatoryName: { type: String, default: "", trim: true, maxlength: 120 },
  registeredAddress: {
    line1: { type: String, default: "", trim: true, maxlength: 200 },
    line2: { type: String, default: "", trim: true, maxlength: 200 },
    city: { type: String, default: "", trim: true, maxlength: 100 },
    state: { type: String, default: "", trim: true, maxlength: 100 },
    pincode: { type: String, default: "", trim: true },
  },
  pickupAddress: {
    line1: { type: String, default: "", trim: true, maxlength: 200 },
    line2: { type: String, default: "", trim: true, maxlength: 200 },
    city: { type: String, default: "", trim: true, maxlength: 100 },
    state: { type: String, default: "", trim: true, maxlength: 100 },
    pincode: { type: String, default: "", trim: true },
  },
  gstinEncrypted: { type: String, required: true, select: false },
  gstinLast4: { type: String, required: true },
  panEncrypted: { type: String, required: true, select: false },
  panLast4: { type: String, required: true },
  bankAccountHolder: { type: String, required: true, trim: true, maxlength: 120 },
  bankAccountType: { type: String, enum: ["current", "savings"], default: "current" },
  bankAccountEncrypted: { type: String, required: true, select: false },
  bankAccountLast4: { type: String, required: true },
  ifscEncrypted: { type: String, required: true, select: false },
  ifscLast4: { type: String, required: true },
  gstVerification: {
    status: { type: String, enum: ["format_checked", "pending", "verified", "failed"], default: "format_checked" },
    source: { type: String, default: "applicant_declaration" },
    checkedAt: { type: Date, default: null },
    legalName: { type: String, default: "", trim: true },
    registrationStatus: { type: String, default: "", trim: true },
  },
  bankVerification: {
    status: { type: String, enum: ["format_checked", "pending", "verified", "failed"], default: "format_checked" },
    source: { type: String, default: "manual_document_review" },
    checkedAt: { type: Date, default: null },
    beneficiaryName: { type: String, default: "", trim: true },
  },
  declarationsAcceptedAt: { type: Date, default: null },
  verificationStatus: { type: String, enum: ["pending", "verified", "rejected"], default: "pending", index: true },
  submittedAt: { type: Date, default: Date.now },
  reviewedAt: { type: Date, default: null },
  reviewedBy: { type: mongoose.Schema.Types.ObjectId, ref: "User", default: null },
  reviewNote: { type: String, default: "", maxlength: 500 },
}, { timestamps: true });

export default mongoose.models.SellerProfile || mongoose.model("SellerProfile", sellerProfileSchema);
