import { useMemo, useState } from "react";
import toast from "react-hot-toast";

const starterSizes = ["0-3M", "3-6M", "6-9M", "9-12M"];
const slug = (value) => String(value || "").toUpperCase().replace(/[^A-Z0-9]+/g, "-").replace(/^-|-$/g, "");

export default function ColorVariantEditor({ variants, setVariants, baseSku, basePrice, lowStockThreshold = 3, onRenameColor }) {
  const [newColor, setNewColor] = useState("");
  const groups = useMemo(() => {
    const map = new Map();
    variants.forEach((variant, index) => { const color = String(variant.color || "Unassigned").trim() || "Unassigned"; if (!map.has(color)) map.set(color, []); map.get(color).push({ variant, index }); });
    return [...map.entries()];
  }, [variants]);
  const update = (index, field, value) => setVariants((current) => current.map((variant, itemIndex) => itemIndex === index ? { ...variant, [field]: ["stock", "price"].includes(field) ? Number(value) : value } : variant));
  const remove = (index) => setVariants((current) => current.filter((_, itemIndex) => itemIndex !== index));
  const sizesToCopy = [...new Set((groups[0]?.[1] || []).map(({ variant }) => variant.size).filter(Boolean))];
  const addColor = () => { const color = newColor.trim(); if (!color) return toast.error("Enter a colour name"); if (groups.some(([name]) => name.toLowerCase() === color.toLowerCase())) return toast.error("This colour already exists"); setVariants((current) => [...current, ...(sizesToCopy.length ? sizesToCopy : starterSizes).map((size) => ({ sku: "", size, color, price: basePrice, stock: 0, active: true }))]); setNewColor(""); };
  const generateSkus = () => setVariants((current) => current.map((variant) => ({ ...variant, sku: `${slug(baseSku) || "PRODUCT"}-${slug(variant.color) || "STYLE"}-${slug(variant.size) || "SIZE"}` })));
  const rename = (oldColor, value) => { const color = value.trim(); if (!color || color === oldColor) return; setVariants((current) => current.map((variant) => (variant.color || "Unassigned") === oldColor ? { ...variant, color } : variant)); onRenameColor?.(oldColor, color); };

  const fields = (variant, index) => <><label><span className="field-label">Size</span><input value={variant.size} onChange={(event) => update(index, "size", event.target.value)} className="field-control py-2"/></label><label><span className="field-label">Stock</span><input type="number" min="0" value={variant.stock} onChange={(event) => update(index, "stock", event.target.value)} className="field-control py-2"/></label><label><span className="field-label">Price</span><input type="number" min="0" value={variant.price ?? basePrice} onChange={(event) => update(index, "price", event.target.value)} className="field-control py-2"/></label><label className="sm:col-span-2"><span className="field-label">SKU</span><input value={variant.sku} onChange={(event) => update(index, "sku", event.target.value.toUpperCase())} className="field-control py-2 font-mono text-xs uppercase"/></label></>;

  return <section className="surface-card p-4 sm:p-6"><div className="flex flex-col justify-between gap-4 md:flex-row md:items-end"><div><h2 className="text-xl font-semibold">Colour styles and inventory</h2><p className="mt-1 text-sm text-slate-500">Manage every colour, size, SKU, price and stock quantity in one listing.</p></div><button type="button" onClick={generateSkus} className="btn-secondary shrink-0 text-sm">Generate all SKUs</button></div><div className="mt-5 grid gap-2 rounded-xl bg-slate-50 p-3 sm:grid-cols-[1fr_auto]"><input value={newColor} onChange={(event) => setNewColor(event.target.value)} onKeyDown={(event) => { if (event.key === "Enter") { event.preventDefault(); addColor(); } }} placeholder="Add another colour, e.g. Maroon" className="field-control"/><button type="button" onClick={addColor} className="btn-primary">+ Add colour</button></div>
    <div className="mt-6 space-y-5">{groups.map(([color, rows]) => { const activeRows = rows.filter(({variant}) => variant.active !== false); const lowCount = activeRows.filter(({variant}) => Number(variant.stock || 0) <= Number(lowStockThreshold)).length; return <article key={color} className="overflow-hidden rounded-2xl border border-slate-200"><header className="flex flex-wrap items-center gap-3 bg-[#eef5f0] px-4 py-3"><span className="grid h-9 w-9 place-items-center rounded-full border-4 border-white bg-[#397153] text-xs font-bold text-white">{color.slice(0,1).toUpperCase()}</span><div className="min-w-0 flex-1"><p className="text-xs font-semibold uppercase tracking-wide text-slate-500">Colour style</p><input defaultValue={color === "Unassigned" ? "" : color} onBlur={(event) => rename(color, event.target.value)} className="mt-0.5 max-w-full border-0 bg-transparent p-0 font-bold text-slate-900 focus:shadow-none"/></div><div className="rounded-xl bg-white px-3 py-2 text-right"><p className="text-sm font-bold">{activeRows.reduce((sum,{variant}) => sum + Number(variant.stock || 0), 0)} units</p><p className={`text-xs ${lowCount ? "text-amber-700" : "text-emerald-700"}`}>{lowCount} low variants</p></div><button type="button" onClick={() => setVariants((current) => current.filter((variant) => (variant.color || "Unassigned") !== color))} className="text-xs font-semibold text-red-600">Remove colour</button></header>
      <div className="grid gap-3 p-3 md:hidden">{rows.map(({variant,index}) => { const low = variant.active !== false && Number(variant.stock || 0) <= Number(lowStockThreshold); return <div key={`${color}-${index}`} className={`rounded-xl border p-3 ${low ? "border-amber-300 bg-amber-50" : "bg-white"}`}><div className="grid grid-cols-2 gap-3">{fields(variant,index)}</div><div className="mt-3 flex items-center justify-between"><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={variant.active !== false} onChange={(event) => update(index,"active",event.target.checked)}/> Active variant</label><button type="button" onClick={() => remove(index)} className="text-xs font-semibold text-red-600">Remove</button></div>{low && <p className="mt-2 text-xs font-semibold text-amber-800">At or below alert level ({lowStockThreshold})</p>}</div>; })}<button type="button" onClick={() => setVariants((current) => [...current,{sku:"",size:"",color:color === "Unassigned" ? "" : color,price:basePrice,stock:0,active:true}])} className="btn-secondary text-sm">+ Add size to {color}</button></div>
      <div className="hidden overflow-x-auto p-4 md:block"><table className="w-full min-w-[760px] text-sm"><thead className="text-left text-xs uppercase tracking-wide text-slate-500"><tr><th className="pb-3">Size</th><th>SKU</th><th>Price</th><th>Stock</th><th>Active</th><th></th></tr></thead><tbody>{rows.map(({variant,index}) => <tr key={`${color}-${index}`} className={variant.active !== false && Number(variant.stock || 0) <= Number(lowStockThreshold) ? "border-t bg-amber-50" : "border-t"}><td className="py-3 pr-2"><input value={variant.size} onChange={(e) => update(index,"size",e.target.value)} className="field-control py-2"/></td><td className="pr-2"><input value={variant.sku} onChange={(e) => update(index,"sku",e.target.value.toUpperCase())} className="field-control py-2 font-mono text-xs"/></td><td className="pr-2"><input type="number" min="0" value={variant.price ?? basePrice} onChange={(e) => update(index,"price",e.target.value)} className="field-control py-2"/></td><td className="pr-2"><input type="number" min="0" value={variant.stock} onChange={(e) => update(index,"stock",e.target.value)} className="field-control py-2"/></td><td><input type="checkbox" checked={variant.active !== false} onChange={(e) => update(index,"active",e.target.checked)}/></td><td><button type="button" onClick={() => remove(index)} className="text-xs text-red-600">Remove</button></td></tr>)}</tbody></table><button type="button" onClick={() => setVariants((current) => [...current,{sku:"",size:"",color:color === "Unassigned" ? "" : color,price:basePrice,stock:0,active:true}])} className="mt-3 text-sm font-semibold text-[#397153]">+ Add size to {color}</button></div></article>; })}</div>{!groups.length && <div className="mt-6 rounded-xl border border-dashed p-8 text-center text-sm text-slate-500">Add the first colour style to begin.</div>}</section>;
}
