import ImageVariantAssignment from "./ImageVariantAssignment";

export default function ColorImageManager({ colors, variants, images, onUpload, onAssign, onMove, onRemove }) {
  const uploadGroups = [{ value: "", label: "Shared images" }, ...colors.map((color) => ({ value: color, label: color }))];
  const groupKey = (image) => image.color || "";
  const firstIndexFor = (color) => images.findIndex((image) => groupKey(image) === color);

  return <section className="surface-card p-5 md:p-6">
    <div><h2 className="text-xl font-semibold">Product photos by colour</h2><p className="mt-1 text-sm text-slate-500">Upload colours separately. New uploads are added to the existing photos.</p></div>
    <div className="mt-5 grid grid-cols-2 gap-3 sm:grid-cols-3 lg:grid-cols-4 xl:grid-cols-5">
      {uploadGroups.map((group) => { const cover = images[firstIndexFor(group.value)]; const count = images.filter((image) => groupKey(image) === group.value).length; return <label key={group.value || "shared"} className="group relative cursor-pointer overflow-hidden rounded-xl border-2 border-dashed border-slate-300 bg-white p-3 transition hover:border-brand-primary hover:bg-emerald-50/40">{cover ? <div className="flex items-center gap-3"><div className="relative h-16 w-14 shrink-0 overflow-hidden rounded-lg"><img src={cover.url} alt="" className="h-full w-full object-cover"/><span className="absolute inset-x-0 bottom-0 bg-black/65 py-0.5 text-center text-[9px] font-semibold text-white">COVER</span></div><div className="min-w-0 text-left"><span className="block truncate text-sm font-semibold">{group.label}</span><span className="mt-1 block text-xs text-slate-500">{count} photo{count === 1 ? "" : "s"}</span><span className="mt-1 block text-xs font-semibold text-brand-primary">+ Add more</span></div></div> : <div className="py-2 text-center"><span className="block text-2xl text-brand-primary">+</span><span className="mt-1 block truncate text-sm font-semibold">{group.label}</span><span className="mt-1 block text-xs text-slate-500">Add photos</span></div>}<input type="file" multiple accept="image/*" onChange={(event) => onUpload(event, group.value)} className="hidden" /></label>; })}
    </div>
    {!images.length ? <div className="mt-6 rounded-xl bg-slate-50 px-4 py-8 text-center text-sm text-slate-500">Choose a colour box above to start adding photos.</div> : <div className="mt-6 grid grid-cols-2 gap-3 sm:grid-cols-3 md:grid-cols-4 lg:grid-cols-5 xl:grid-cols-6">{images.map((image, index) => { const key = groupKey(image); const groupIndexes = images.map((item, itemIndex) => groupKey(item) === key ? itemIndex : -1).filter((itemIndex) => itemIndex >= 0); const position = groupIndexes.indexOf(index); const isCover = position === 0; return <article key={image.id || image.url} className={`min-w-0 rounded-xl border-2 bg-white p-2 ${isCover ? "border-brand-primary" : "border-slate-200"}`}><div className="relative"><img src={image.url} alt="" className="aspect-square w-full rounded-lg object-cover"/>{isCover && <span className="absolute left-1.5 top-1.5 rounded bg-brand-primary px-1.5 py-0.5 text-[10px] font-semibold text-white">{key ? `${key} cover` : "Shared cover"}</span>}</div><ImageVariantAssignment color={image.color || ""} size={image.size || ""} colors={colors} variants={variants} onChange={(assignment) => onAssign(index, assignment)} />{!isCover && <button type="button" onClick={() => onMove(index, groupIndexes[0])} className="mt-2 w-full rounded-lg bg-emerald-50 py-1.5 text-[11px] font-semibold text-brand-primary">Set as {key || "shared"} cover</button>}<div className="mt-2 grid grid-cols-3 gap-1"><button type="button" disabled={position === 0} onClick={() => onMove(index, groupIndexes[position - 1])} className="rounded bg-slate-100 py-1 text-xs disabled:opacity-30" aria-label="Move earlier in this colour">←</button><button type="button" disabled={position === groupIndexes.length - 1} onClick={() => onMove(index, groupIndexes[position + 1])} className="rounded bg-slate-100 py-1 text-xs disabled:opacity-30" aria-label="Move later in this colour">→</button><button type="button" onClick={() => onRemove(index)} className="rounded bg-red-50 py-1 text-xs text-red-600" aria-label="Remove image">×</button></div></article>; })}</div>}
    <p className="mt-4 text-xs text-slate-500">Every colour has its own cover. Use “Set as cover” or the arrows to arrange photos within that colour.</p>
  </section>;
}
