import { FieldError } from "./ListingValidation";
const departments = ["Girls", "Boys", "Clothing", "Footwear", "Bags & Accessories", "Beauty & Personal Care", "Home & Kitchen", "Electronics", "Mobile Accessories", "Toys & Games", "Baby Essentials", "Sports & Outdoors", "Books & Stationery", "Grocery", "Health & Wellness", "Pet Supplies", "Automotive", "Tools & Garden"];

export function CategoryField({ value, onChange, error }) {
  return <label><span className="field-label">Category *</span><input required aria-label="Category *" aria-invalid={Boolean(error)} aria-describedby={`listing-category-hint${error ? " listing-category-error" : ""}`} list="catalogue-departments" name="category" value={value} onChange={onChange} placeholder="Choose or enter a category" className="field-control"/><datalist id="catalogue-departments">{departments.map((label) => <option key={label} value={label.toLowerCase().replace(/[^a-z0-9]+/g, "-")}>{label}</option>)}</datalist><span id="listing-category-hint" className="mt-1 block text-xs text-slate-500">Custom categories are supported. Use the same category name for related products.</span><FieldError name="category" message={error}/></label>;
}

export default function GeneralListingFields({ form, onChange, errors = {} }) {
  const apparel = ["girls", "boys", "new-arrivals", "clothing", "fashion"].includes(String(form.category).toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, ""));
  return <section className="surface-card mt-5 p-6"><h2 className="text-xl font-semibold">Product details & fulfilment</h2><p className="mt-2 text-sm text-slate-500">Choose the inventory structure, add useful specifications and confirm this product’s tax information. Prices include tax.</p><div className="mt-5 grid gap-4 md:grid-cols-2">
    <label><span className="field-label">Inventory structure</span><select name="productType" value={form.productType} onChange={onChange} className="field-control"><option value="simple">Single SKU — no customer options</option><option value="variable">Multiple options or styles</option></select></label>
    {form.productType !== "simple" && <label><span className="field-label">Option label</span><input name="optionLabel" value={form.optionLabel} onChange={onChange} placeholder="Size, Capacity, Pack, Model…" maxLength="30" className="field-control"/></label>}
    {[["brand","Brand"],["subcategory","Subcategory"],["modelNumber","Model / product code"],["manufacturer","Manufacturer"],["countryOfOrigin","Country of origin"],["warranty","Warranty / guarantee"],["packageContents","What’s in the box"]].map(([name,label]) => <label key={name}><span className="field-label">{label}</span><input name={name} value={form[name]} onChange={onChange} className="field-control"/></label>)}
    <label><span className="field-label">Tax calculation</span><select name="gstMode" value={form.gstMode || (apparel ? "apparel" : "custom")} onChange={onChange} className="field-control">{apparel && <option value="apparel">Apparel rate by transaction value</option>}<option value="custom">Confirmed product GST percentage</option></select></label>
    {(form.gstMode === "custom" || (!form.gstMode && !apparel)) && <label><span className="field-label">GST percentage *</span><input aria-label="GST percentage *" aria-invalid={Boolean(errors.gstRate)} aria-describedby={errors.gstRate ? "listing-gstRate-error" : undefined} name="gstRate" type="number" min="0" max="100" step="0.01" value={form.gstRate} onChange={onChange} className="field-control"/><span className="mt-1 block text-xs text-slate-500">Use the rate confirmed for this product and HSN, including 0 for exempt goods. Consult your tax adviser if unsure.</span><FieldError name="gstRate" message={errors.gstRate}/></label>}
    <label className="md:col-span-2"><span className="field-label">Specifications / key features</span><textarea name="specifications" rows="4" value={form.specifications} onChange={onChange} placeholder="One feature per line, e.g. Capacity: 1 litre" maxLength="3000" className="field-control"/></label>
    <div className="md:col-span-2"><h3 className="font-semibold">Packed unit measurements</h3><p className="mt-1 text-xs text-slate-500">Include packaging. Confirm the final parcel measurements when booking shipment, especially for orders with multiple items.</p></div>
    {[["weightKg","Weight (kg)"],["lengthCm","Length (cm)"],["widthCm","Width (cm)"],["heightCm","Height (cm)"]].map(([name,label]) => <label key={name}><span className="field-label">{label}</span><input aria-label={label} aria-invalid={Boolean(errors[name])} aria-describedby={errors[name] ? `listing-${name}-error` : undefined} type="number" min="0.001" step="0.001" name={name} value={form[name]} onChange={onChange} className="field-control"/><FieldError name={name} message={errors[name]}/></label>)}
  </div></section>;
}
