const money = (value) => Number.isFinite(Number(value)) && value !== "" ? `₹${Number(value).toLocaleString("en-IN", { maximumFractionDigits: 2 })}` : "Not set";
const valueOrEmpty = (value) => String(value ?? "").trim() || "Not provided";

export default function ListingReview({ form, variants, images, onEdit }) {
  const active = variants.filter((item) => item.active !== false);
  const stock = active.reduce((sum, item) => sum + Number(item.stock || 0), 0);
  return <section className="surface-card overflow-hidden" aria-label="Listing review">
    <header className="border-b bg-slate-50/70 p-5 sm:p-6"><p className="eyebrow">Final check</p><h2 className="mt-2 text-2xl font-semibold">Review your listing</h2><p className="mt-2 text-sm text-slate-500">Check the customer information, every active option and the packed measurements before saving.</p></header>
    <div className="space-y-6 p-5 sm:p-6">
      <div className="flex flex-col gap-5 sm:flex-row">{images[0] ? <img src={images[0].url} alt="Listing cover preview" className="h-44 w-full rounded-xl border bg-slate-50 object-contain sm:w-36"/> : <div className="grid h-36 w-36 place-items-center rounded-xl border border-dashed text-sm text-slate-500">No cover photo</div>}<div className="min-w-0 flex-1"><p className="text-xs uppercase tracking-wide text-slate-500">{valueOrEmpty(form.category).replaceAll("-", " ")}</p><h3 className="mt-2 break-words text-xl font-semibold">{form.name || "Untitled listing"}</h3><p className="mt-2 text-sm text-slate-500">{form.brand || "Brand not provided"} · {form.productType === "simple" ? "Single SKU" : `${form.optionLabel || "Option"} choices`}</p><p className="mt-4 text-2xl font-bold text-brand-primary">{money(form.price)}</p><p className="mt-1 text-sm text-slate-500">MRP {money(form.mrp)} · Inclusive of tax</p><button type="button" onClick={() => onEdit(0)} className="mt-3 text-sm font-semibold text-brand-primary underline">Edit product details</button></div></div>
      <dl className="grid grid-cols-3 gap-3 text-center">{[["Active SKUs", active.length], ["Photos", images.length], ["Available units", stock]].map(([label, value]) => <div key={label} className="rounded-xl bg-slate-50 p-3"><dt className="text-xs text-slate-500">{label}</dt><dd className="mt-1 text-lg font-bold">{value}</dd></div>)}</dl>
      <div className="border-t pt-5"><h3 className="font-semibold">Description and specifications</h3><p className="mt-3 whitespace-pre-line break-words text-sm leading-6 text-slate-600">{form.description || "Add a description before publishing."}</p>{form.specifications && <p className="mt-3 whitespace-pre-line break-words text-sm leading-6 text-slate-600">{form.specifications}</p>}</div>
      <div className="border-t pt-5"><div className="flex items-center justify-between gap-3"><h3 className="font-semibold">Options and inventory</h3><button type="button" onClick={() => onEdit(1)} className="text-sm font-semibold text-brand-primary underline">Edit inventory</button></div><ul className="mt-3 space-y-2">{variants.map((item, index) => <li key={index} className="rounded-xl border p-3 text-sm"><p className="break-words font-medium">{[item.color, item.size].filter(Boolean).join(" · ") || "Unnamed option"} {item.active === false && <span className="ml-2 text-xs text-slate-500">Inactive</span>}</p><p className="mt-1 break-all text-xs text-slate-500">SKU {item.sku || "Not set"}</p><p className="mt-2">{money(item.price ?? form.price)} · {Number(item.stock || 0)} units</p></li>)}</ul></div>
      <div className="border-t pt-5"><div className="flex items-center justify-between gap-3"><h3 className="font-semibold">Product photos</h3><button type="button" onClick={() => onEdit(2)} className="text-sm font-semibold text-brand-primary underline">Edit photos</button></div><div className="mt-3 flex flex-wrap gap-2">{images.map((image, index) => <img key={image.id || index} src={image.url} alt={`Listing photo ${index + 1}`} className="h-20 w-16 rounded-lg border bg-slate-50 object-contain"/>)}</div><p className="mt-2 text-xs text-slate-500">The first photo is the cover. Match option photos to the correct style.</p></div>
      <div className="border-t pt-5"><h3 className="font-semibold">Fulfilment and product details</h3><dl className="mt-3 grid gap-3 text-sm sm:grid-cols-2">{[["Base SKU",form.baseSku],["HSN",form.hsnCode],["Packed weight",form.weightKg ? `${form.weightKg} kg` : ""],["Packed dimensions",[form.lengthCm,form.widthCm,form.heightCm].every(Boolean) ? `${form.lengthCm} × ${form.widthCm} × ${form.heightCm} cm` : ""],["Country of origin",form.countryOfOrigin],["Warranty",form.warranty],["Package contents",form.packageContents]].map(([label,value]) => <div key={label}><dt className="text-xs text-slate-500">{label}</dt><dd className="mt-1 break-words">{valueOrEmpty(value)}</dd></div>)}</dl></div>
    </div>
  </section>;
}
